import {MigrationInterface, QueryRunner} from "typeorm";

export class ChangeTimestampToTimestamptz1743875433606 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "verificationTokenCreatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "verificationTokenCreatedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "passwordResetTokenCreatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "passwordResetTokenCreatedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "identifierChangeTokenCreatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "identifierChangeTokenCreatedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "session" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "session" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "publishedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "publishedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "closedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "closedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "rejectedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "rejectedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "editedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "editedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "settledAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "settledAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "rejectedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "rejectedAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "prevSettledAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "prevSettledAt" TIMESTAMP WITH TIME ZONE`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" DROP COLUMN "insertedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" ADD "insertedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "job_record" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_record_buffer" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_tag" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" DROP COLUMN "insertedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" ADD "insertedAt" TIMESTAMP(3) NOT NULL`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "cache_item" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "history_entry" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "prevSettledAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "prevSettledAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "rejectedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "rejectedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "settledAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "settledAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "balance_entry" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_translation" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "collection_asset" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "editedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "editedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "rejectedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "rejectedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "closedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "closedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "publishedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "publishedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "deletedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "job_post_asset" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_value_translation" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "facet_translation" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" ADD "deletedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" ADD "deletedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "administrator" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deletedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" ADD "deletedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "session" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "session" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "identifierChangeTokenCreatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "identifierChangeTokenCreatedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "passwordResetTokenCreatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "passwordResetTokenCreatedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "verificationTokenCreatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "verificationTokenCreatedAt" TIMESTAMP`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "updatedAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" DROP COLUMN "createdAt"`, undefined);
        await queryRunner.query(`ALTER TABLE "authentication_method" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`, undefined);
   }

}
