import z from 'zod';

export const HistoryEntryType = z.enum([
    'CUSTOMER_EMAIL_UPDATE_REQUESTED',
    'CUSTOMER_EMAIL_UPDATE_VERIFIED',
    'CUSTOMER_DETAIL_UPDATED',
    'CUSTOMER_PASSWORD_RESET_REQUESTED',
    'CUSTOMER_PASSWORD_RESET_VERIFIED',
    'CUSTOMER_PASSWORD_UPDATED',
    'CUSTOMER_REGISTERED',
    'CUSTOMER_VERIFIED',
]);
